### PR TITLE
pydantic post endpoints - frontend changes

### PR DESCRIPTION
**Pull request by maximi4321**
# Summary

This PR adapts the api on the frontend to send post requests without using query parameters.

## Type of change

- Refactoring.

## Changes

- FormData is used to send the data in the POST requests of the `experiment`, `run` and `runner` endpoints.

## How to Test

1. Go to `DashAI/DashAI/front` and run `yarn build`
2. Go back to `DashAI/` and run `python -c "import DashAI;DashAI.run()"`
3. Test `experiment` and `run` endpoints by creating an experiment.
4. Test `runner` endpoint by running the experiment created before.

### CODE REVIEW

**Review by pbadillatorrealba — COMMENTED** [review]
I think the changes fit well with the modifications of the back. 
But here I renew the question: why use FormData when we could perfectly send raw json?

**Comment by cristian-tamblay** [comment]
POST endpoints use JSON format now. Plase review it @maximi4321 and @pbadillatorrealba so we can merge

**Comment by maximi4321** [comment]
The changes work well for me!

**Review by pbadillatorrealba — APPROVED** [review]
Looks good!

**Pull request merged**
